# Versão do docker-compose: 2
# Referência: https://docs.docker.com/compose/compose-file://docs.docker.com/compose/compose-file/
version: '2'

services:
  enade:
    dns: ["8.8.8.8"]
    # image: ifbaeunapolis/simulados:latest
    build: jenkins/
    mem_limit: 512m
    cpu_shares: 20
    ports:
      - "8080:8080" # Porta do Jenkins
      - "50000:50000"
      - "10022:22" # SSH do Gogs
      - "3000:3000" # Porta do Gogs HTTP

  gogs:
    image: gogs/gogs
    network_mode: service:enade
    depends_on:
      - enade
    volumes:
      - ./gogs/config/:/data/gogs/conf/
      - ./gogs/gogs-data/:/data/

  mysql:
    image: mariadb:10.1.12
    network_mode: service:enade
    depends_on:
      - enade
    volumes:
      - ./db-data/mysql-data/:/var/lib/mysql/
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_DATABASE=gogs
      - MYSQL_ROOT_PASSWORD=FCQW3HGWpsLPmb4h
